# https://taskfile.dev

version: '3'

tasks:
  check_errors:
    cmds:
      - flake8 --extend-ignore E501
         --exclude .git,__pycache__,venv,docs/source/conf.py,old,build,dist
         --max-complexity 10
      - mypy --exclude venv 
                --exclude __pycache__ 
                --exclude .mypy_cache .
    silent: true
  lint:
    cmds:
      - isort *
      - black -l 79 
        --exclude __pycache__ 
        --exclude venv .
    silent: true
  run:
    cmds:
      - python main.py
    silent: true
